FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o auth ./cmd/auth 

FROM alpine

WORKDIR /app

COPY --from=builder /app/configs/auth-server.yml ./configs/
COPY --from=builder /app/auth .

EXPOSE 8081

CMD ["./auth"]