services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_DB: expkit
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: