FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o auth ./cmd/auth 

FROM scratch

WORKDIR /app

COPY --from=builder /app/auth .
COPY --from=builder /app/configs/auth-server.yml ./configs/
COPY --from=builder /app/.env .

EXPOSE 8081

CMD ["./auth"]